---
# Source: cloud-ml-pipeline/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-ml-pipeline
  labels:
    helm.sh/chart: cloud-ml-pipeline-0.1.0
    app.kubernetes.io/name: cloud-ml-pipeline
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: cloud-ml-pipeline/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cloud-ml-pipeline
  labels:
    helm.sh/chart: cloud-ml-pipeline-0.1.0
    app.kubernetes.io/name: cloud-ml-pipeline
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: cloud-ml-pipeline
    app.kubernetes.io/instance: dev
---
# Source: cloud-ml-pipeline/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-ml-pipeline
  labels:
    helm.sh/chart: cloud-ml-pipeline-0.1.0
    app.kubernetes.io/name: cloud-ml-pipeline
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloud-ml-pipeline
      app.kubernetes.io/instance: dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloud-ml-pipeline
        app.kubernetes.io/instance: dev
    spec:
      serviceAccountName: cloud-ml-pipeline
      securityContext:
        {}
      containers:
        - name: cloud-ml-pipeline
          securityContext:
            {}
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
