apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-adservice
spec:
  selector:
    matchLabels:
      app: eshop-adservice
  template:
    metadata:
      labels:
        app: eshop-adservice
    spec:
      containers:
        - name: eshop-adservice
          image: gcr.io/architect-certification-289902/2301/25/eshop-adservice:3
          ports:
          - containerPort: 8095
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/eshop_db"
            - name: GOOGLE_CLOUD_PROJECT
              value: architect-certification-289902
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-adservice
spec:
  type: ClusterIP
  selector:
    app: eshop-adservice
  ports:
  - port: 8095